slogan: "随心而行"

theme: bootstrap
inverse: true

menu:
  - title: "首页"
    url: 
    intro: "Homepage"
    icon: "fa fa-home"
  - title: "归档"
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: "分类"
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: "标签"
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: Wiki
    url: wiki
    intro: "笔记"
    icon: "fa fa-tasks"
  - title: "订阅"
    url: "atom.xml"
    intro: "订阅本站"
    icon: "fa fa-rss"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

selflinks:
  - title: "My Github"
    url: https://github.com/xpc-yx
    intro: "My Github account."
    icon: "fa fa-github"

friendlinks:
  - title: klion26
    url: http://www.klion26.com
    intro: "klion26的博客"
    icon: "fa fa-user"
    
adlinks:
  - title: "My Github"
    url: https://github.com/xpc-yx
    intro: "My Github account."
    icon: "fa fa-github"
    
widgets:
- search
- category
- tagcloud
- recent_posts  
- selflinks
- friendlinks
- adlinks

rss: "atom.xml"
fancybox: true
favicon: favicon.ico

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: true
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

wangyiyun_gentie: true

#打赏
donate:
  enable: true
  text: Enjoy it ? Donate me !  欣赏此文？求鼓励，求支持！
  wechat: https://c1.staticflickr.com/8/7735/28088007526_175a52a7d4_n.jpg
  alipay: https://c1.staticflickr.com/8/7388/27528799304_c1c54e95e6_n.jpg
  
homepage_url: http://xpc-yx.com